export enum Permissions {
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USERS = 'CREATE_USERS',
  EDIT_USERS = 'EDIT_USERS',
  DELETE_USERS = 'DELETE_USERS',

  VIEW_PERMISSIONS = 'VIEW_PERMISSIONS',
  CREATE_PERMISSIONS = 'CREATE_PERMISSIONS',
  EDIT_PERMISSIONS = 'EDIT_PERMISSIONS',
  DELETE_PERMISSIONS = 'DELETE_PERMISSIONS',

  VIEW_ACTIVITIES = 'VIEW_ACTIVITIES',
  CREATE_ACTIVITIES = 'CREATE_ACTIVITIES',
  EDIT_ACTIVITIES = 'EDIT_ACTIVITIES',
  DELETE_ACTIVITIES = 'DELETE_ACTIVITIES',

  VIEW_ACTIVITY_TYPES = 'VIEW_ACTIVITY_TYPES',
  CREATE_ACTIVITY_TYPES = 'CREATE_ACTIVITY_TYPES',
  EDIT_ACTIVITY_TYPES = 'EDIT_ACTIVITY_TYPES',
  DELETE_ACTIVITY_TYPES = 'DELETE_ACTIVITY_TYPES',

  GENERATE_ACTIVITIES_REPORT = 'GENERATE_ACTIVITIES_REPORT',
}
